export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const REMOVE_BUDGET = 'REMOVE_BUDGET';
export const GET_BUDGET = 'GET_BUDGET';
export const ADD_BUDGET = 'ADD_BUDGET';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const UPDATE_MEAL = 'UPDATE_MEAL';
export const REMOVE_MEAL = 'REMOVE_MEAL';
export const GET_MEAL = 'GET_MEAL';
export const ADD_MEAL = 'ADD_MEAL';
export const GET_MEALS = 'GET_MEALS';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_EVALUATION';
export const GET_PRODUCT = 'GET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_CATEGORY_PRODUCTS = 'GET_CATEGORY_PRODUCTS';
export const GET_MEAL_PRODUCTS = 'GET_MEAL_PRODUCTS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';
